
# try:
#     mi_lista = [1, 2, 3]
#     print(mi_lista[4])  # Intento acceder a un √≠ndice que no existe
# except IndexError as e:
#     print('An exception occurred', e, type(e))  # Captura el error espec√≠fico de √≠ndice
# finally:
#     print("FIN DEL PROGRAMA desde el finally, como cerrar archivos, conexiones, etc.")
    
# print("FIN DEL PROGRAMA")
# print("FIN DEL PROGRAMA")

try:
    a = float(input('Ingresa un dividendo: '))
    b = int(input('Ingresa un divisor: '))
    resultado = a / b
    print('‚úÖ el resultado es:', resultado)
except ValueError as e:
    print('‚ùå debe ingresar un nuemro üî¢', e, type(e))
except ZeroDivisionError as e:
    print('‚ùå no se puede dividir por cero 0Ô∏è‚É£', e, type(e))
except BaseException as e:
    print('‚ùå EL ERROR ES DE TIPO BASE ', e, type(e))
except Exception as e:
    print('‚ùå el error no lo se pero debe ser ', e, type(e))
# else:
#     print('‚úÖ el resultado es:', resultado)
finally:
    print('üîöFIN DEL PROGRAMA')


print(" ‚≠êFIN DEL PROGRAMA DESDE FUERA‚≠ê ")